import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container">
          <h1>
            Welcome to my blog!
          </h1>
          <span>
            Read <Link href="/posts">this page</Link>
          </span>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  return {
    props: {
      page: 'Home'
    }
  }
}